// Language Configuration
export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
  { code: 'bn', name: 'বাংলা', flag: '🇮🇳' }
];

export const translations = {
  en: {
    "Type \"DELETE\" to confirm account deletion:": "Type \"DELETE\" to confirm account deletion:",
    dashboard: 'Dashboard',
    overview: 'Overview',
    analytics: 'Analytics',
    tasks: 'Tasks',
    marketplace: 'Marketplace',
    weather: 'Weather',
    community: 'Community',
    settings: 'Settings',
    cropHealth: 'Crop Health',
    soilMoisture: 'Soil Moisture',
    temperature: 'Temperature',
    growthRate: 'Growth Rate',
    todaysTasks: "Today's Tasks",
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    weatherForecast: 'Weather Forecast',
    farmStats: 'Farm Statistics',
    totalYield: 'Total Yield',
    activeCrops: 'Active Crops',
    farmSize: 'Farm Size',
    efficiency: 'Efficiency',
    soilAnalysis: 'Soil Analysis',
    aiAssistant: 'AI Assistant',
    scheduleTask: 'Schedule Task',
    session: 'Expert Consultation',
    viewAnalytics: 'View Analytics',
    addNewTask: 'Add New Task',
    pendingTasks: 'Pending Tasks',
    inProgress: 'In Progress',
    completed: 'Completed',
    allTasks: 'All Tasks',
    search: 'Search...',
    profile: 'Profile',
    notifications: 'Notifications',
    logout: 'Logout',
    chatbot: 'AI Assistant',
    chatbotSubtitle: '24/7 Smart Farming Support',
    placeholder: 'Type your question here...',
    quickQuestions: 'Quick Questions',
    aiFeatures: 'AI Features',
    chatStats: 'Chat Stats',
    uploadImage: 'Upload Image',
    takePhoto: 'Take Photo',
    dragDrop: 'Drag & drop images here or click to browse',
    analyzing: 'Analyzing image...',
    thinking: 'AI is thinking...',
    saveKey: 'Save Key',
    apiKeyPrompt: 'Please enter your Google AI API key:',
    apiKeyPlaceholder: 'Enter your API key...',
    apiKeyNote: 'Your API key is stored locally.',
    // New Keys
    cropRecommendations: 'Crop Recommendations',
    recommendedCrops: 'Recommended Crops',
    viewAll: 'View All',
    loadingWeather: 'Loading weather data...',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    feelsLike: 'Feels like',
    yourLocation: 'Your Location',
    yield: 'Yield',
    demand: 'Demand',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    fetchingData: 'Fetching live data...',
    expertCall: 'Expert Call',
    noChange: 'Same'
  },
  hi: {
    "Image size should be less than 5MB', 'error": "छवि का आकार 5एमबी से कम होना चाहिए', 'त्रुटि",
    "✅ Profile picture updated!', 'success": "✅ प्रोफ़ाइल चित्र अपडेट किया गया!', 'सफलता",
    "❌ Failed to upload image', 'error": "❌ छवि अपलोड करने में विफल', 'त्रुटि",
    "✅ Profile updated successfully!', 'success": "✅ प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!', 'सफलता",
    "❌ Failed to update profile', 'error": "❌ प्रोफ़ाइल अपडेट करने में विफल', 'त्रुटि",
    "❌ Passwords do not match', 'error": "❌ पासवर्ड मेल नहीं खाते', 'त्रुटि",
    "❌ Password must be at least 6 characters', 'error": "❌ पासवर्ड कम से कम 6 अक्षर का होना चाहिए', 'त्रुटि",
    "✅ Password changed successfully!', 'success": "✅ पासवर्ड सफलतापूर्वक बदल गया!', 'सफलता",
    "❌ Failed to change password', 'error": "❌ पासवर्ड बदलने में विफल', 'त्रुटि",
    "✅ Notification preferences saved!', 'success": "✅ अधिसूचना प्राथमिकताएँ सहेजी गईं!', 'सफलता",
    "❌ Failed to update notifications', 'error": "❌ सूचनाएं अद्यतन करने में विफल', 'त्रुटि",
    "✅ Privacy settings updated!', 'success": "✅ गोपनीयता सेटिंग्स अपडेट की गईं!', 'सफलता",
    "❌ Failed to update privacy', 'error": "❌ गोपनीयता अद्यतन करने में विफल', 'त्रुटि",
    "Type \"DELETE\" to confirm account deletion:": "खाता हटाने की पुष्टि के लिए \"हटाएं\" टाइप करें:",
    "❌ Account deletion cancelled', 'error": "❌ खाता हटाना रद्द किया गया', 'त्रुटि",
    "✅ Account deleted successfully', 'success": "✅ खाता सफलतापूर्वक हटा दिया गया', 'सफलता",
    "❌ Failed to delete account', 'error": "❌ खाता हटाने में विफल', 'त्रुटि",
    "a": "ए",
    "✅ Data exported successfully!', 'success": "✅ डेटा सफलतापूर्वक निर्यात किया गया!', 'सफलता",
    "❌ Failed to export data', 'error": "❌ डेटा निर्यात करने में विफल', 'त्रुटि",
    "Settings": "सेटिंग्स",
    "Manage your account preferences and settings": "अपनी खाता प्राथमिकताएं और सेटिंग प्रबंधित करें",
    "Logout": "लॉग आउट",
    "Profile Information": "प्रोफाइल की जानकारी",
    "Language": "भाषा",
    "/marketplace/my-listings": "/बाज़ार/मेरी-सूची",
    "/marketplace/my-orders": "/बाज़ार/मेरे-आदेश",
    "/marketplace/mandi-prices": "/बाज़ार/मंडी-कीमतें",
    "/seller/fertilizers": "/विक्रेता/उर्वरक",
    "✅ Listing created successfully!', 'success": "✅ सूची सफलतापूर्वक बनाई गई!', 'सफलता",
    "❌ Failed to create listing', 'error": "❌ लिस्टिंग बनाने में विफल', 'त्रुटि",
    "✅ Listing deleted', 'success": "✅ सूची हटा दी गई', 'सफलता",
    "❌ Failed to delete listing', 'error": "❌ सूची हटाने में विफल', 'त्रुटि",
    "✅ Order placed successfully!', 'success": "✅ ऑर्डर सफलतापूर्वक दिया गया!', 'सफलता",
    "Marketplace": "बाजार",
    "Buy and sell agricultural products": "कृषि उत्पाद खरीदें और बेचें",
    "Farm Produce": "कृषि उपज",
    "Fertilizers": "उर्वरक",
    "Loading analytics...": "विश्लेषण लोड हो रहा है...",
    "Crop Health Analytics": "फसल स्वास्थ्य विश्लेषण",
    "Add New Crop": "नई फसल जोड़ें",
    "No Crops Yet": "अभी तक कोई फसल नहीं",
    "Start by adding your first crop to track its health and progress with AI-powered analysis.": "एआई-संचालित विश्लेषण के साथ अपने स्वास्थ्य और प्रगति को ट्रैक करने के लिए अपनी पहली फसल को जोड़कर शुरुआत करें।",
    "AI Disease Diagnostic": "एआई रोग निदान",
    "Upload a clear photo of your plant's leaf to identify potential diseases and get an immediate severity rating and treatment plan.": "संभावित बीमारियों की पहचान करने और तत्काल गंभीरता रेटिंग और उपचार योजना प्राप्त करने के लिए अपने पौधे की पत्ती की एक स्पष्ट तस्वीर अपलोड करें।",
    "T": "टी",
    "/community": "/समुदाय",
    "": "",
    "Failed to post. Are you logged in?": "पोस्ट करने में विफल. क्या आप लॉग इन हैं?",
    "Loading community...": "समुदाय लोड हो रहा है...",
    "Farmer Community": "किसान समुदाय",
    "Connect, learn, and grow together": "जुड़ें, सीखें और एक साथ बढ़ें",
    "New Post": "नई पोस्ट",
    "Members": "सदस्यों",
    "Posts Today": "आज पोस्ट",
    "Trending": "रुझान",
    "Experts": "विशेषज्ञों",
    "Create a Post": "एक पोस्ट बनाएं",
    "Share your farming experience, ask questions, or give advice...": "अपना खेती का अनुभव साझा करें, प्रश्न पूछें, या सलाह दें...",
    dashboard: 'डैशबोर्ड',
    overview: 'अवलोकन',
    analytics: 'विश्लेषण',
    tasks: 'कार्य',
    marketplace: 'बाज़ार',
    weather: 'मौसम',
    community: 'समुदाय',
    settings: 'सेटिंग्स',
    cropHealth: 'फसल स्वास्थ्य',
    soilMoisture: 'मिट्टी की नमी',
    temperature: 'तापमान',
    growthRate: 'वृद्धि दर',
    todaysTasks: 'आज के कार्य',
    quickActions: 'त्वरित कार्य',
    recentActivity: 'हाल की गतिविधि',
    weatherForecast: 'मौसम पूर्वानुमान',
    farmStats: 'खेत के आंकड़े',
    totalYield: 'कुल उत्पादन',
    activeCrops: 'सक्रिय फसलें',
    farmSize: 'खेत का आकार',
    efficiency: 'दक्षता',
    soilAnalysis: 'मिट्टी विश्लेषण',
    aiAssistant: 'एआई सहायक',
    scheduleTask: 'कार्य निर्धारित करें',
    session: 'विशेषज्ञ कॉल',
    viewAnalytics: 'विश्लेषण देखें',
    addNewTask: 'नया कार्य जोड़ें',
    pendingTasks: 'लंबित कार्य',
    inProgress: 'प्रगति में',
    completed: 'पूर्ण',
    allTasks: 'सभी कार्य',
    search: 'खोजें...',
    profile: 'प्रोफ़ाइल',
    notifications: 'सूचनाएं',
    logout: 'लॉग आउट',
    chatbot: 'AI सहायक',
    chatbotSubtitle: '24/7 स्मार्ट कृषि सहायता',
    placeholder: 'अपना सवाल यहाँ लिखें...',
    quickQuestions: 'त्वरित प्रश्न',
    aiFeatures: 'AI सुविधाएं',
    chatStats: 'चैट आंकड़े',
    uploadImage: 'तस्वीर अपलोड करें',
    takePhoto: 'फोटो लें',
    dragDrop: 'तस्वीरें यहाँ खींचें या ब्राउज़ करने के लिए क्लिक करें',
    analyzing: 'विशेषण हो रहा है...',
    thinking: 'AI सोच रहा है...',
    saveKey: 'सेव करें',
    apiKeyPrompt: 'अपनी Google AI API key डालें:',
    apiKeyPlaceholder: 'API key डालें...',
    apiKeyNote: 'आपकी API key सुरक्षित है।',
    // New Keys
    cropRecommendations: 'फसल सिफारिशें',
    recommendedCrops: 'अनुशंसित फसलें',
    viewAll: 'सभी देखें',
    loadingWeather: 'मौसम डेटा लोड हो रहा है...',
    humidity: 'नमी',
    windSpeed: 'हवा की गति',
    feelsLike: 'महसूस होता है',
    yourLocation: 'आपका स्थान',
    yield: 'पैदावार',
    demand: 'मांग',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'निम्न',
    fetchingData: 'डेटा प्राप्त किया जा रहा है...',
    noChange: 'समान'
  },
  pa: {
    "Type \"DELETE\" to confirm account deletion:": "ਖਾਤਾ ਮਿਟਾਉਣ ਦੀ ਪੁਸ਼ਟੀ ਕਰਨ ਲਈ \"DELETE\" ਟਾਈਪ ਕਰੋ:",
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    overview: 'ਸਾਰਾਂਸ਼',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    tasks: 'ਕੰਮ',
    marketplace: 'ਬਾਜ਼ਾਰ',
    weather: 'ਮੌਸਮ',
    community: 'ਭਾਈਚਾਰਾ',
    settings: 'ਸੈਟਿੰਗਜ਼',
    cropHealth: 'ਫਸਲ ਦੀ ਸਿਹਤ',
    soilMoisture: 'ਮਿੱਟੀ ਦੀ ਨਮੀ',
    temperature: 'ਤਾਪਮਾਨ',
    growthRate: 'ਵਿਕਾਸ ਦਰ',
    todaysTasks: 'ਅੱਜ ਦੇ ਕੰਮ',
    quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
    recentActivity: 'ਹਾਲ ਦੀ ਗਤੀਵਿਧੀ',
    weatherForecast: 'ਮੌਸਮ ਪੂਰਵ-ਅਨੁਮਾਨ',
    farmStats: 'ਖੇਤ ਦੇ ਅੰਕੜੇ',
    totalYield: 'ਕੁੱਲ ਉਤਪਾਦਨ',
    activeCrops: 'ਸਰਗਰਮ ਫਸਲਾਂ',
    farmSize: 'ਖੇਤ ਦਾ ਆਕਾਰ',
    efficiency: 'ਕੁਸ਼ਲਤਾ',
    soilAnalysis: 'ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    aiAssistant: 'ਏਆਈ ਸਹਾਇਕ',
    scheduleTask: 'ਕੰਮ ਨਿਰਧਾਰਿਤ ਕਰੋ',
    session: 'ਮਾਹਿਰ ਕਾਲ',
    viewAnalytics: 'ਵਿਸ਼ਲੇਸ਼ਣ ਦੇਖੋ',
    addNewTask: 'ਨਵਾਂ ਕੰਮ ਜੋੜੋ',
    pendingTasks: 'ਬਕਾਇਆ ਕੰਮ',
    inProgress: 'ਪ੍ਰਗਤੀ ਵਿੱਚ',
    completed: 'ਮੁਕੰਮਲ',
    allTasks: 'ਸਾਰੇ ਕੰਮ',
    search: 'ਖੋਜੋ...',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    logout: 'ਲਾੱਗ ਆਉਟ',
    chatbot: 'AI ਸਹਾਇਕ',
    chatbotSubtitle: '24/7 ਸਮਾਰਟ ਖੇਤੀ ਸਹਾਇਤਾ',
    placeholder: 'ਆਪਣਾ ਸਵਾਲ ਇੱਥੇ ਲਿਖੋ...',
    quickQuestions: 'ਤੁਰੰਤ ਸਵਾਲ',
    aiFeatures: 'AI ਸੁਵਿਧਾਵਾਂ',
    chatStats: 'ਚੈਟ ਅੰਕੜੇ',
    uploadImage: 'ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
    takePhoto: 'ਫੋਟੋ ਖਿੱਚੋ',
    dragDrop: 'ਫੋਟੋਆਂ ਇੱਥੇ ਖਿੱਚੋ ਜਾਂ ਬ੍ਰਾਊਜ਼ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...',
    thinking: 'AI ਸੋਚ ਰਿਹਾ ਹੈ...',
    saveKey: 'ਸੇਵ ਕਰੋ',
    apiKeyPrompt: 'ਆਪਣੀ API key ਪਾਓ:',
    apiKeyPlaceholder: 'API key ਪਾਓ...',
    apiKeyNote: 'ਤੁਹਾਡੀ API key ਸੁਰੱਖਿਅਤ ਹੈ।',
    // New Keys
    cropRecommendations: 'ਫਸਲ ਦੀ ਸਿਫ਼ਾਰਿਸ਼',
    recommendedCrops: 'ਸਿਫ਼ਾਰਿਸ਼ ਫਸਲਾਂ',
    viewAll: 'ਸਭ ਦੇਖੋ',
    loadingWeather: 'ਮੌਸਮ ਡੇਟਾ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    humidity: 'ਨਮੀ',
    windSpeed: 'ਹਵਾ ਦੀ ਗਤੀ',
    feelsLike: 'ਮਹਿਸੂਸ ਹੁੰਦਾ ਹੈ',
    yourLocation: 'ਤੁਹਾਡਾ ਸਥਾਨ',
    yield: 'ਝਾੜ',
    demand: 'ਮੰਗ',
    high: 'ਉੱਚ',
    medium: 'ਮੱਧਮ',
    low: 'ਘੱਟ',
    fetchingData: 'ਡੇਟਾ ਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    noChange: 'ਸਮਾਨ'
  },
  mr: {
    "Type \"DELETE\" to confirm account deletion:": "खाते हटविण्याची पुष्टी करण्यासाठी \"DELETE\" टाइप करा:",
    dashboard: 'डॅशबोर्ड',
    overview: 'आढावा',
    analytics: 'विश्लेषण',
    tasks: 'कामे',
    marketplace: 'बाजारपेठ',
    weather: 'हवामान',
    community: 'समुदाय',
    settings: 'सेटिंग्ज',
    cropHealth: 'पीक आरोग्य',
    soilMoisture: 'मातीतील ओलावा',
    temperature: 'तापमान',
    growthRate: 'वाढ दर',
    todaysTasks: 'आजची कामे',
    quickActions: 'त्वरित कृती',
    recentActivity: 'अलीकडील क्रियाकलाप',
    weatherForecast: 'हवामान अंदाज',
    farmStats: 'शेत आकडेवारी',
    totalYield: 'एकूण उत्पादन',
    activeCrops: 'सक्रिय पिके',
    farmSize: 'शेत आकार',
    efficiency: 'कार्यक्षमता',
    soilAnalysis: 'माती विश्लेषण',
    aiAssistant: 'AI सहाय्यक',
    scheduleTask: 'काम शेड्यूल्ड करा',
    session: 'तज्ञ कॉल',
    viewAnalytics: 'विश्लेषण पहा',
    addNewTask: 'नवीन काम जोडा',
    pendingTasks: 'प्रलंबित कामे',
    inProgress: 'प्रगतीपथावर',
    completed: 'पूर्ण',
    allTasks: 'सर्व कामे',
    search: 'शोधा...',
    profile: 'प्रोफाइल',
    notifications: 'सूचना',
    logout: 'लॉग आउट',
    chatbot: 'AI सहाय्यक',
    chatbotSubtitle: '24/7 स्मार्ट कृषी मदत',
    placeholder: 'येथे तुमचा प्रश्न विचारा...',
    quickQuestions: 'त्वरित प्रश्न',
    aiFeatures: 'AI वैशिष्ट्ये',
    chatStats: 'चॅट आकडेवारी',
    uploadImage: 'फोटो अपलोड करा',
    takePhoto: 'फोटो काढा',
    dragDrop: 'फोटो येथे ड्रॅग करा किंवा ब्राउझ करा',
    analyzing: 'विश्लेषण करत आहे...',
    thinking: 'AI विचार करत आहे...',
    saveKey: 'सेव्ह करा',
    apiKeyPrompt: 'तुमची API key टाका:',
    apiKeyPlaceholder: 'API key टाका...',
    apiKeyNote: 'तुमची API key सुरक्षित आहे.',
    // New Keys
    cropRecommendations: 'पीक शिफारसी',
    recommendedCrops: 'शिफारस केलेली पिके',
    viewAll: 'सर्व पहा',
    loadingWeather: 'हवामान माहिती लोड होत आहे...',
    humidity: 'आद्रता',
    windSpeed: 'वाऱ्याचा वेग',
    feelsLike: 'जाणवते',
    yourLocation: 'तुमचे स्थान',
    yield: 'उत्पादन',
    demand: 'मागणी',
    high: 'जास्त',
    medium: 'मध्यम',
    low: 'कमी',
    fetchingData: 'माहिती मिळवत आहे...',
    noChange: 'समान'
  },
  gu: {
    "Type \"DELETE\" to confirm account deletion:": "એકાઉન્ટ કાઢી નાખવાની પુષ્ટિ કરવા માટે \"DELETE\" લખો:",
    dashboard: 'ડેશબોર્ડ',
    overview: 'વિહંગાવલોકન',
    analytics: 'વિશ્લેષણ',
    tasks: 'કાર્યો',
    marketplace: 'બજાર',
    weather: 'હવામાન',
    community: 'સમુદાય',
    settings: 'સેટિંગ્સ',
    cropHealth: 'પાક આરોગ્ય',
    soilMoisture: 'જમીનમાં ભેજ',
    temperature: 'તાપમાન',
    growthRate: 'વૃદ્ધિ દર',
    todaysTasks: 'आજના કાર્યો',
    quickActions: 'ઝડપી કાર્યો',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    weatherForecast: 'હવામાનની આગાહી',
    farmStats: 'ખેતરના આંકડા',
    totalYield: 'કુલ ઉત્પાદન',
    activeCrops: 'સક્રિય પાક',
    farmSize: 'ખેતરનું કદ',
    efficiency: 'કાર્યક્ષમતા',
    soilAnalysis: 'જમીન વિશ્લેષણ',
    aiAssistant: 'AI સહાયક',
    scheduleTask: 'કાર્ય નિર્ધારિત કરો',
    session: 'નિષ્ણાત કોલ',
    viewAnalytics: 'વિશ્લેષણ જુઓ',
    addNewTask: 'નવું કાર્ય ઉમેરો',
    pendingTasks: 'બાકી કાર્યો',
    inProgress: 'પ્રગતિમાં',
    completed: 'પૂર્ણ',
    allTasks: 'બધા કાર્યો',
    search: 'શોધો...',
    profile: 'પ્રોફાઇલ',
    notifications: 'સૂચનાઓ',
    logout: 'લૉગ આઉટ',
    chatbot: 'AI સહાયક',
    chatbotSubtitle: '24/7 સ્માર્ટ ખેતી સહાય',
    placeholder: 'તમારો પ્રશ્ન અહીં પૂછો...',
    quickQuestions: 'ઝડપી પ્રશ્નો',
    aiFeatures: 'AI વિશેષતાઓ',
    chatStats: 'ચેટ આંકડા',
    uploadImage: 'ફોટો અપલોડ કરો',
    takePhoto: 'ફોટો લો',
    dragDrop: 'ફોટો અહીં ખેંચો',
    analyzing: 'વિશ્લેષણ થઈ રહ્યું છે...',
    thinking: 'AI વિચારી રહ્યું છે...',
    saveKey: 'સાચવો',
    apiKeyPrompt: 'તમારી API key દાખલ કરો:',
    apiKeyPlaceholder: 'API key નાખો...',
    apiKeyNote: 'તમારી API key સુરક્ષિત રીતે સાચવવામાં આવે છે.',
    // New Keys
    cropRecommendations: 'પાક ભલામણો',
    recommendedCrops: 'ભલામણ કરેલ પાક',
    viewAll: 'બધું જુઓ',
    loadingWeather: 'હવામાન ડેટા લોડ થઈ રહ્યો છે...',
    humidity: 'ભેજ',
    windSpeed: 'પવનની ગતિ',
    feelsLike: 'અનુભવાય છે',
    yourLocation: 'તમારું સ્થાન',
    yield: 'ઉપજ',
    demand: 'માંગ',
    high: 'ઉચ્ચ',
    medium: 'મધ્યમ',
    low: 'નીચું',
    fetchingData: 'ડેટા મેળવી રહ્યા છીએ...',
    noChange: 'સમાન'
  },
  ta: {
    "Type \"DELETE\" to confirm account deletion:": "கணக்கு நீக்குதலை உறுதிப்படுத்த \"DELETE\" என உள்ளிடவும்:",
    dashboard: 'டாஷ்போர்டு',
    overview: 'கண்ணோட்டம்',
    analytics: 'பகுப்பாய்வு',
    tasks: 'பணிகள்',
    marketplace: 'சந்தை',
    weather: 'வானிலை',
    community: 'சமூகம்',
    settings: 'அமைப்புகள்',
    cropHealth: 'பயிர் ஆரோக்கியம்',
    soilMoisture: 'மண் ஈரம்',
    temperature: 'வெப்பநிலை',
    growthRate: 'வளர்ச்சி விகிதம்',
    todaysTasks: 'இன்றைய பணிகள்',
    quickActions: 'விரைவான செயல்கள்',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    weatherForecast: 'வானிலை முன்னறிவிப்பு',
    farmStats: 'பண்ணை புள்ளிவிவரங்கள்',
    totalYield: 'மொத்த மகசூல்',
    activeCrops: 'செயலில் உள்ள பயிர்கள்',
    farmSize: 'பண்ணை அளவு',
    efficiency: 'திறன்',
    soilAnalysis: 'மண் பகுப்பாய்வு',
    aiAssistant: 'AI உதவியாளர்',
    scheduleTask: 'பணியைத் திட்டமிடு',
    session: 'நிபுணர் அழைப்பு',
    viewAnalytics: 'பகுப்பாய்வைக் காண்க',
    addNewTask: 'புதிய பணியைச் சேர்',
    pendingTasks: 'நிலுவையில் உள்ள பணிகள்',
    inProgress: 'செயலில் உள்ளது',
    completed: 'முடிந்தது',
    allTasks: 'அனைத்துப் பணிகள்',
    search: 'தேடு...',
    profile: 'சுயவிவரம்',
    notifications: 'அறிவிப்புகள்',
    logout: 'வெளியேறு',
    chatbot: 'AI உதவியாளர்',
    chatbotSubtitle: '24/7 ஸ்மார்ட் விவசாய உதவி',
    placeholder: 'கேள்வியைக் கேட்கவும்...',
    quickQuestions: 'கேள்விகள்',
    aiFeatures: 'AI அம்சங்கள்',
    chatStats: 'அரட்டை விவரங்கள்',
    uploadImage: 'பதிவேற்றவும்',
    takePhoto: 'புகைப்படம் எடுக்கவும்',
    dragDrop: 'இழுக்கவும் அல்லது தேடவும்',
    analyzing: 'ஆய்வு செய்யப்படுகிறது...',
    thinking: 'AI யோசிக்கிறது...',
    saveKey: 'சேமிக்கவும்',
    apiKeyPrompt: 'API key ஐ உள்ளிடவும்:',
    apiKeyPlaceholder: 'API key ஐ உள்ளிடவும்...',
    apiKeyNote: 'உங்கள் API key பாதுகாப்பானது.',
    // New Keys
    cropRecommendations: 'பயிர் பரிந்துரைகள்',
    recommendedCrops: 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    viewAll: 'அனைத்தையும் காண்க',
    loadingWeather: 'வானிலை தரவு ஏற்றப்படுகிறது...',
    humidity: 'ஈரப்பதம்',
    windSpeed: 'காற்றின் வேகம்',
    feelsLike: 'உணரப்படுகிறது',
    yourLocation: 'உங்கள் இருப்பிடம்',
    yield: 'மகசூல்',
    demand: 'தேவை',
    high: 'அதிகம்',
    medium: 'நடுத்தரம்',
    low: 'குறைவு',
    fetchingData: 'தரவு பெறப்படுகிறது...',
    noChange: 'மாற்றமில்லை'
  },
  te: {
    "Type \"DELETE\" to confirm account deletion:": "ఖాతా తొలగింపును నిర్ధారించడానికి \"తొలగించు\" అని టైప్ చేయండి:",
    dashboard: 'డాష్‌బోర్డ్',
    overview: 'అవలోకనం',
    analytics: 'విశ్లేషణలు',
    tasks: 'పనులు',
    marketplace: 'మార్కెట్ ప్లేస్',
    weather: 'వాతావరణం',
    community: 'కమ్యూనిటీ',
    settings: 'సెట్టింగ్‌లు',
    cropHealth: 'పంట ఆరోగ్యం',
    soilMoisture: 'మట్టి తేమ',
    temperature: 'ఉష్ణోగ్రత',
    growthRate: 'వృద్ధి రేటు',
    todaysTasks: 'నేటి పనులు',
    quickActions: 'త్వరిత చర్యలు',
    recentActivity: 'ఇటీవలి కార్యాచరణ',
    weatherForecast: 'వాతావరణ సూచన',
    farmStats: 'ఫామ్ గణాంకాలు',
    totalYield: 'మొత్తం దిగుబడి',
    activeCrops: 'క్రియాశీల పంటలు',
    farmSize: 'ఫామ్ పరిమాణం',
    efficiency: 'సామర్థ్యం',
    soilAnalysis: 'మట్టి విశ్లేషణ',
    aiAssistant: 'AI అసిస్టెంట్',
    scheduleTask: 'పనిని షెడ్యూల్ చేయండి',
    session: 'నిపుణుల కాల్',
    viewAnalytics: 'విశ్లేషణలను చూడండి',
    addNewTask: 'కొత్త పనిని జోడించండి',
    pendingTasks: 'పెండింగ్ పనులు',
    inProgress: 'కొనసాగుతోంది',
    completed: 'పూర్తయింది',
    allTasks: 'అన్ని పనులు',
    search: 'శోధించండి...',
    profile: 'ప్రొఫైల్',
    notifications: 'నోటిఫికేషన్లు',
    logout: 'లాగ్ అవుట్',
    chatbot: 'AI అసిస్టెంట్',
    chatbotSubtitle: '24/7 స్మార్ట్ వ్యవసాయ సహాయం',
    placeholder: 'ప్రశ్నను ఇక్కడ అడగండి...',
    quickQuestions: 'త్వరిత ప్రశ్నలు',
    aiFeatures: 'AI ఫీచర్లు',
    chatStats: 'చాట్ గణాంకాలు',
    uploadImage: 'అప్‌లోడ్ చేయండి',
    takePhoto: 'ఫోటో తీయండి',
    dragDrop: 'డ్రాగ్ చేయండి లేదా బ్రౌజ్ చేయండి',
    analyzing: 'విశ్లేషించబడుతోంది...',
    thinking: 'AI ఆలోచిస్తోంది...',
    saveKey: 'సేవ్ చేయండి',
    apiKeyPrompt: 'API key ని నమోదు చేయండి:',
    apiKeyPlaceholder: 'API key ని నమోదు చేయండి...',
    apiKeyNote: 'మీ API key సురక్షితం.',
    // New Keys
    cropRecommendations: 'పంట సిఫార్సులు',
    recommendedCrops: 'సిఫార్సు చేసిన పంటలు',
    viewAll: 'అన్నీ చూడండి',
    loadingWeather: 'వాతావరణ డేటా లోడ్ అవుతోంది...',
    humidity: 'తేమ',
    windSpeed: 'గాలి వేగం',
    feelsLike: 'అనిపిస్తోంది',
    yourLocation: 'నీ స్థానం',
    yield: 'దిగుబడి',
    demand: 'డిమాండ్',
    high: 'ఎక్కువ',
    medium: 'మధ్యస్థం',
    low: 'తక్కువ',
    fetchingData: 'డేటాను పొందుతోంది...',
    noChange: 'మార్పు లేదు'
  },
  bn: {
    "Type \"DELETE\" to confirm account deletion:": "অ্যাকাউন্ট মুছে ফেলা নিশ্চিত করতে \"DELETE\" টাইপ করুন:",
    dashboard: 'ড্যাশবোর্ড',
    overview: 'সারসংক্ষেপ',
    analytics: 'বিশ্লেষণ',
    tasks: 'কাজ',
    marketplace: 'বাজার',
    weather: 'আবহাওয়া',
    community: 'সম্প্রদায়',
    settings: 'সেটিংস',
    cropHealth: 'ফসলের স্বাস্থ্য',
    soilMoisture: 'মাটির আর্দ্রতা',
    temperature: 'তাপমাত্রা',
    growthRate: 'বৃদ্ধির হার',
    todaysTasks: 'আজকের কাজ',
    quickActions: 'দ্রুত পদক্ষেপ',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    weatherForecast: 'আবহাওয়ার পূর্বাভাস',
    farmStats: 'খামারের পরিসংখ্যান',
    totalYield: 'মোট ফলন',
    activeCrops: 'সক্রিয় ফসল',
    farmSize: 'খামারের আকার',
    efficiency: 'দক্ষতা',
    soilAnalysis: 'মাটি বিশ্লেষণ',
    aiAssistant: 'AI সহকারী',
    scheduleTask: 'কাজ নির্ধারণ করুন',
    session: 'বিশেষজ্ঞের কল',
    viewAnalytics: 'বিশ্লেষণ দেখুন',
    addNewTask: 'নতুন কাজ যোগ করুন',
    pendingTasks: 'বাকি কাজ',
    inProgress: 'চলমান',
    completed: 'সম্পন্ন',
    allTasks: 'সব কাজ',
    search: 'খুঁজুন...',
    profile: 'প্রোফাইল',
    notifications: 'বিজ্ঞপ্তি',
    logout: 'লগ আউট',
    chatbot: 'AI সহকারী',
    chatbotSubtitle: '24/7 স্মার্ট কৃষি সহায়তা',
    placeholder: 'আপনার প্রশ্ন জিজ্ঞাসা করুন...',
    quickQuestions: 'দ্রুত প্রশ্ন',
    aiFeatures: 'AI বৈশিষ্ট্য',
    chatStats: 'পরিসংখ্যান',
    uploadImage: 'আপলোড করুন',
    takePhoto: 'ছবি তুলুন',
    dragDrop: 'টেনে আনুন বা ব্রাউজ করুন',
    analyzing: 'বিশ্লেষণ করা হচ্ছে...',
    thinking: 'AI চিন্তা করছে...',
    saveKey: 'সেভ করুন',
    apiKeyPrompt: 'API key লিখুন:',
    apiKeyPlaceholder: 'API key লিখুন...',
    apiKeyNote: 'আপনার API key সুরক্ষিত।',
    // New Keys
    cropRecommendations: 'ফসলের সুপারিশ',
    recommendedCrops: 'প্রস্তাবিত ফসল',
    viewAll: 'সব দেখুন',
    loadingWeather: 'আবহাওয়া তথ্য লোড হচ্ছে...',
    humidity: 'আর্দ্রতা',
    windSpeed: 'বাতাসের গতি',
    feelsLike: 'অনুভব হচ্ছে',
    yourLocation: 'আপনার অবস্থান',
    yield: 'ফলন',
    demand: 'চাহিদা',
    high: 'উচ্চ',
    medium: 'মাঝারি',
    low: 'নিম্ন',
    fetchingData: 'তথ্য সংগ্রহ করা হচ্ছে...',
    noChange: 'একই'
  },
  kn: {
    "Type \"DELETE\" to confirm account deletion:": "ಖಾತೆ ಅಳಿಸುವಿಕೆಯನ್ನು ಖಚಿತಪಡಿಸಲು \"DELETE\" ಎಂದು ಟೈಪ್ ಮಾಡಿ:",
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    overview: 'ಅವಲೋಕನ',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    tasks: 'ಕೆಲಸಗಳು',
    marketplace: 'ಮಾರುಕಟ್ಟೆ',
    weather: 'ಹವಾಮಾನ',
    community: 'ಸಮುದಾಯ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    cropHealth: 'ಬೆಳೆ ಆರೋಗ್ಯ',
    soilMoisture: 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
    temperature: 'ತಾಪಮಾನ',
    growthRate: 'ಬೆಳವಣಿಗೆಯ ದರ',
    todaysTasks: 'ಇಂದಿನ ಕೆಲಸಗಳು',
    quickActions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    weatherForecast: 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    farmStats: 'ಕೃಷಿ ಅಂಕಿಅಂಶಗಳು',
    totalYield: 'ಒಟ್ಟು ಇಳುವರಿ',
    activeCrops: 'ಸಕ್ರಿಯ ಬೆಳೆಗಳು',
    farmSize: 'ಫಾರ್ಮ್ ಗಾತ್ರ',
    efficiency: 'ದಕ್ಷತೆ',
    soilAnalysis: 'ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣೆ',
    aiAssistant: 'AI ಅಸಿಸ್ಟೆಂಟ್',
    scheduleTask: 'ಕೆಲಸವನ್ನು ನಿಗದಿಪಡಿಸಿ',
    session: 'ತಜ್ಞರ ಕರೆ',
    viewAnalytics: 'ವಿಶ್ಲೇಷಣೆ ವೀಕ್ಷಿಸಿ',
    addNewTask: 'ಹೊಸ ಕೆಲಸ ಸೇರಿಸಿ',
    pendingTasks: 'ಬಾಕಿ ಇರುವ ಕೆಲಸಗಳು',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    allTasks: 'ಎಲ್ಲಾ ಕೆಲಸಗಳು',
    search: 'ಹುಡುಕಿ...',
    profile: 'ಪ್ರೊಫೈಲ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    chatbot: 'AI ಅಸಿಸ್ಟೆಂಟ್',
    chatbotSubtitle: '24/7 ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಹಾಯ',
    placeholder: 'ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ...',
    quickQuestions: 'ತ್ವರಿತ ಪ್ರಶ್ನೆಗಳು',
    aiFeatures: 'AI ವೈಶಿಷ್ಟ್ಯಗಳು',
    chatStats: 'ಅಂಕಿಅಂಶಗಳು',
    uploadImage: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    dragDrop: 'ಎಳೆಯಿರಿ ಅಥವಾ ಬ್ರೌಸ್ ಮಾಡಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    thinking: 'AI ಯೋಚಿಸುತ್ತಿದೆ...',
    saveKey: 'ಸೇವ್ ಮಾಡಿ',
    apiKeyPrompt: 'API key ಅನ್ನು ನಮೂದಿಸಿ:',
    apiKeyPlaceholder: 'API key ನಮೂದಿಸಿ...',
    apiKeyNote: 'ನಿಮ್ಮ API key ಸುರಕ್ಷಿತವಾಗಿದೆ.',
    // New Keys
    cropRecommendations: 'ಬೆಳೆ ಶಿಫಾರಸುಗಳು',
    recommendedCrops: 'ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಳೆಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    loadingWeather: 'ಹವಾಮಾನ ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    humidity: 'ತೇವಾಂಶ',
    windSpeed: 'ಗಾಳಿಯ ವೇಗ',
    feelsLike: 'ಅನಿಸುತ್ತದೆ',
    yourLocation: 'ನಿಮ್ಮ ಸ್ಥಳ',
    yield: 'ಇಳುವರಿ',
    demand: 'ಬೇಡಿಕೆ',
    high: 'ಹೆಚ್ಚು',
    medium: 'ಮಧ್ಯಮ',
    low: 'ಕಡಿಮೆ',
    fetchingData: 'ಡೇಟಾ ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    noChange: 'ಬದಲಾವಣೆ ಇಲ್ಲ'
  },
  ml: {
    "Type \"DELETE\" to confirm account deletion:": "അക്കൗണ്ട് ഇല്ലാതാക്കൽ സ്ഥിരീകരിക്കാൻ \"DELETE\" എന്ന് ടൈപ്പ് ചെയ്യുക:",
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    overview: 'അവലോകനം',
    analytics: 'അനലിറ്റിക്സ്',
    tasks: 'ചുമതലകൾ',
    marketplace: 'കമ്പോളം',
    weather: 'കാലാവസ്ഥ',
    community: 'കമ്മ്യൂണിറ്റി',
    settings: 'ക്രമീകരണങ്ങൾ',
    cropHealth: 'വിള ആരോഗ്യ നില',
    soilMoisture: 'മണ്ണിലെ ഈർപ്പം',
    temperature: 'താപനില',
    growthRate: 'വളർച്ചാ നിരക്ക്',
    todaysTasks: 'ഇന്നത്തെ ചുമതലകൾ',
    quickActions: 'ദ്രുത നടപടികൾ',
    recentActivity: 'സമീപകാല പ്രവർത്തനങ്ങൾ',
    weatherForecast: 'കാലാവസ്ഥാ പ്രവചനം',
    farmStats: 'ഫാം സ്ഥിതിവിവരങ്ങൾ',
    totalYield: 'ആകെ വിളവ്',
    activeCrops: 'സജീവ വിളകൾ',
    farmSize: 'ഫാം വലിപ്പം',
    efficiency: 'കാര്യക്ഷമത',
    soilAnalysis: 'മണ്ണ് പരിശോധന',
    aiAssistant: 'AI അസിസ്റ്റന്റ്',
    scheduleTask: 'ചുമതല ഷെഡ്യൂൾ ചെയ്യുക',
    session: 'വിദഗ്ദ്ധ സേവനം',
    viewAnalytics: 'വിശകലനം കാണുക',
    addNewTask: 'പുതിയ ജോലി ചേർക്കുക',
    pendingTasks: 'തീർപ്പല്ലാത്തവ',
    inProgress: 'പുരോഗതിയിൽ',
    completed: 'പൂർത്തിയായി',
    allTasks: 'എല്ലാ ചുമതലകളും',
    search: 'തിരയുക...',
    profile: 'പ്രൊഫൈൽ',
    notifications: 'അറിയിപ്പുകൾ',
    logout: 'ലോഗ് ഔട്ട്',
    chatbot: 'AI അസിസ്റ്റന്റ്',
    chatbotSubtitle: '24/7 സ്മാർട്ട് കൃഷി സഹായം',
    placeholder: 'ചോദ്യം ചോദിക്കുക...',
    quickQuestions: 'ചോദ്യങ്ങൾ',
    aiFeatures: 'AI ഫീച്ചറുകൾ',
    chatStats: 'സ്റ്റാറ്റസ്',
    uploadImage: 'അപ്‌ലോഡ് ചെയ്യുക',
    takePhoto: 'ഫോട്ടോ എടുക്കുക',
    dragDrop: 'വലിച്ചിടുക അല്ലെങ്കിൽ ബ്രൗസ് ചെയ്യുക',
    analyzing: 'വിശകലനം ചെയ്യുന്നു...',
    thinking: 'AI ചിന്തിക്കുന്നു...',
    saveKey: 'സേവ് ചെയ്യുക',
    apiKeyPrompt: 'API key നൽകുക:',
    apiKeyPlaceholder: 'API key നൽകുക...',
    apiKeyNote: 'നിങ്ങളുടെ API key സുരക്ഷിതമാണ്.',
    // New Keys
    cropRecommendations: 'വിള ശുപാർശകൾ',
    recommendedCrops: 'ശുപാർശ ചെയ്യുന്ന വിളകൾ',
    viewAll: 'എല്ലാം കാണുക',
    loadingWeather: 'കാലാവസ്ഥാ വിവരങ്ങൾ...',
    humidity: 'ഈർപ്പം',
    windSpeed: 'കാറ്റിന്റെ വേഗത',
    feelsLike: 'അനുഭവപ്പെടുന്നു',
    yourLocation: 'നിങ്ങളുടെ സ്ഥലം',
    yield: 'വിളവ്',
    demand: 'ഡിമാൻഡ്',
    high: 'ഉയർന്നത്',
    medium: 'മിതമായ',
    low: 'കുറഞ്ഞത്',
    fetchingData: 'വിവരങ്ങൾ ശേഖരിക്കുന്നു...',
    noChange: 'മാറ്റമില്ല'
  }
};