// Language Configuration
export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', name: 'বাংলা', flag: '🇮🇳' }
];

export const translations = {
  en: {
    dashboard: 'Dashboard',
    overview: 'Overview',
    analytics: 'Analytics',
    tasks: 'Tasks',
    marketplace: 'Marketplace',
    weather: 'Weather',
    community: 'Community',
    settings: 'Settings',
    cropHealth: 'Crop Health',
    soilMoisture: 'Soil Moisture',
    temperature: 'Temperature',
    growthRate: 'Growth Rate',
    todaysTasks: "Today's Tasks",
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    weatherForecast: 'Weather Forecast',
    farmStats: 'Farm Statistics',
    totalYield: 'Total Yield',
    activeCrops: 'Active Crops',
    farmSize: 'Farm Size',
    efficiency: 'Efficiency',
    soilAnalysis: 'Soil Analysis',
    aiAssistant: 'AI Assistant',
    scheduleTask: 'Schedule Task',
    expertCall: 'Expert Call',
    viewAnalytics: 'View Analytics',
    addNewTask: 'Add New Task',
    pendingTasks: 'Pending Tasks',
    inProgress: 'In Progress',
    completed: 'Completed',
    allTasks: 'All Tasks',
    search: 'Search...',
    profile: 'Profile',
    notifications: 'Notifications',
    logout: 'Logout',
    chatbot: 'AI Assistant',
    quickQuestions: 'Quick Questions',
    aiFeatures: 'AI Features',
    chatStats: 'Chat Stats'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    overview: 'अवलोकन',
    analytics: 'विश्लेषण',
    tasks: 'कार्य',
    marketplace: 'बाजार',
    weather: 'मौसम',
    community: 'समुदाय',
    settings: 'सेटिंग्स',
    cropHealth: 'फसल स्वास्थ्य',
    soilMoisture: 'मिट्टी की नमी',
    temperature: 'तापमान',
    growthRate: 'वृद्धि दर',
    todaysTasks: 'आज के कार्य',
    quickActions: 'त्वरित कार्य',
    recentActivity: 'हाल की गतिविधि',
    weatherForecast: 'मौसम पूर्वानुमान',
    farmStats: 'खेत के आंकड़े',
    totalYield: 'कुल उत्पादन',
    activeCrops: 'सक्रिय फसलें',
    farmSize: 'खेत का आकार',
    efficiency: 'दक्षता',
    soilAnalysis: 'मिट्टी विश्लेषण',
    aiAssistant: 'एआई सहायक',
    scheduleTask: 'कार्य निर्धारित करें',
    expertCall: 'विशेषज्ञ कॉल',
    viewAnalytics: 'विश्लेषण देखें',
    addNewTask: 'नया कार्य जोड़ें',
    pendingTasks: 'लंबित कार्य',
    inProgress: 'प्रगति में',
    completed: 'पूर्ण',
    allTasks: 'सभी कार्य',
    search: 'खोजें...',
    profile: 'प्रोफ़ाइल',
    notifications: 'सूचनाएं',
    logout: 'लॉग आउट',
    chatbot: 'AI सहायक',
    quickQuestions: 'त्वरित प्रश्न',
    aiFeatures: 'AI सुविधाएं',
    chatStats: 'चैट आंकड़े'
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    overview: 'ਸਾਰਾਂਸ਼',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    tasks: 'ਕੰਮ',
    marketplace: 'ਬਾਜ਼ਾਰ',
    weather: 'ਮੌਸਮ',
    community: 'ਭਾਈਚਾਰਾ',
    settings: 'ਸੈਟਿੰਗਜ਼',
    cropHealth: 'ਫਸਲ ਦੀ ਸਿਹਤ',
    soilMoisture: 'ਮਿੱਟੀ ਦੀ ਨਮੀ',
    temperature: 'ਤਾਪਮਾਨ',
    growthRate: 'ਵਿਕਾਸ ਦਰ',
    todaysTasks: 'ਅੱਜ ਦੇ ਕੰਮ',
    quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
    recentActivity: 'ਹਾਲ ਦੀ ਗਤੀਵਿਧੀ',
    weatherForecast: 'ਮੌਸਮ ਪੂਰਵ-ਅਨੁਮਾਨ',
    farmStats: 'ਖੇਤ ਦੇ ਅੰਕੜੇ',
    totalYield: 'ਕੁੱਲ ਉਤਪਾਦਨ',
    activeCrops: 'ਸਰਗਰਮ ਫਸਲਾਂ',
    farmSize: 'ਖੇਤ ਦਾ ਆਕਾਰ',
    efficiency: 'ਕੁਸ਼ਲਤਾ',
    soilAnalysis: 'ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    aiAssistant: 'ਏਆਈ ਸਹਾਇਕ',
    scheduleTask: 'ਕੰਮ ਨਿਰਧਾਰਿਤ ਕਰੋ',
    expertCall: 'ਮਾਹਿਰ ਕਾਲ',
    viewAnalytics: 'ਵਿਸ਼ਲੇਸ਼ਣ ਦੇਖੋ',
    addNewTask: 'ਨਵਾਂ ਕੰਮ ਜੋੜੋ',
    pendingTasks: 'ਬਕਾਇਆ ਕੰਮ',
    inProgress: 'ਪ੍ਰਗਤੀ ਵਿੱਚ',
    completed: 'ਮੁਕੰਮਲ',
    allTasks: 'ਸਾਰੇ ਕੰਮ',
    search: 'ਖੋਜੋ...',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    logout: 'ਲਾੱਗ ਆਉਟ',
    chatbot: 'AI ਸਹਾਇਕ',
    quickQuestions: 'ਤੁਰੰਤ ਸਵਾਲ',
    aiFeatures: 'AI ਸੁਵਿਧਾਵਾਂ',
    chatStats: 'ਚੈਟ ਅੰਕੜੇ'
  }
};